name: Deploy to server

on: push
env:
  NAME: ENRRIN PAGOADA

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo $NAME"      

  second_job:
    if: ${{github.ref == 'refs/heads/main'}}
    needs: first_job
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo Segundo $NAME"