name: Deploy to server

on: push
env:
  NAME: ENRRIN PAGOADA

jobs:
  first_job:
    name: Primer Job
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo $NAME"  

      - name: Working dir
        run: ls -al

      - name: Action
        uses: actions/checkout@latest

      - name: Working dir after action
        run: ls -al    

  second_job:
    name: Segundo Job
    if: ${{github.ref == 'refs/heads/main'}}
    needs: first_job
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo Segundo $NAME"