name: Deploy to server

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo {{github.ref}}"      

  second_job:
    if: ${{github.ref == 'ref/heads/main'}}
    needs: first_job
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo Segundo"